spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dealDB?useSSL=false
    username: root
    password:
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: false